# Generated by Django 4.2.11 on 2024-03-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(choices=[('Large Fruit', 'Large Fruit'), ('Medium Fruit', 'Medium Fruit'), ('Small Fruit', 'Small Fruit'), ('Parfait', 'Parfait'), ('Grilled Wrap', 'Grilled Wrap'), ('Spicy Wrap', 'Spicy Wrap'), ('Kale Salad', 'Kale Salad'), ('Market Salad', 'Market Salad'), ('Southwest Salad', 'Southwest Salad'), ('Cobb Salad', 'Cobb Salad'), ('Side Salad', 'Side Salad')], max_length=100)),
                ('quantity', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20')], max_length=100)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
