# Generated by Django 4.2.11 on 2024-03-16 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='Southwaest_Salad',
            new_name='Southwest_Salad',
        ),
    ]
